import React from "react"
import ToastItem from "./ToastItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ToastItem,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7072%3A913",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "link": figma.boolean('Link?'),
      // "text": figma.string('Text'),
      // "icon": figma.boolean('Icon?'),
      // "icon24": figma.instance('Icon-24'),
      // "dismiss": figma.boolean('Dismiss?')
    },
    example: (props) => <ToastItem toast={/* TODO */} onClose={/* TODO */} />,
  },
)
