import React from "react"
import { Link } from "./Link"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Link,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=163%3A562",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      inverted: figma.boolean("Inverted?"),
      media: figma.string("Text"),
      type: figma.string("Text"),
      // No matching props could be found for these Figma properties:
      // "iconLeft": figma.boolean('Icon left?'),
      // "iconRight": figma.boolean('Icon right?'),
      // "iconRight20": figma.instance('Icon right-20'),
      // "iconLeft20": figma.instance('Icon left-20'),
      // "text": figma.string('Text'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Focus": "focus",
      //   "Active": "active"
      // })
    },
    example: (props) => (
      <Link inverted={props.inverted} media={props.media} type={props.type} />
    ),
  },
)
