import React from "react"
import MenuItem from "./MenuItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6416%3A11142",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Active: true,
      }),
      focusable: figma.enum("State", {
        Focus: true,
      }),
      // No matching props could be found for these Figma properties:
      // "number": figma.string('Number'),
      // "selected": figma.boolean('Selected?')
    },
    example: (props) => (
      <MenuItem
        text={/* TODO */}
        disabled={props.disabled}
        focusable={props.focusable}
      />
    ),
  },
)
