import figma from '@figma/code-connect';
import Input from './Input';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Input, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2685%3A7021', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.enum('State', {
      Disabled: true,
    }),
    readonly: figma.enum('State', {
      'Read-only': true,
    }),
    focused: figma.boolean('Focus?'),
    placeholder: figma.string('Suffix'),
    focusable: figma.boolean('Focus?'),
    hasTVPreferredFocus: figma.boolean('Focus?'),
    'aria-disabled': figma.enum('State', {
      Disabled: true,
    }),
    // No matching props could be found for these Figma properties:
    // "helperText": figma.boolean('Helper text?'),
    // "label": figma.string('Label'),
    // "validation": figma.string('Validation'),
    // "helperText": figma.string('Helper text'),
    // "value": figma.string('Value'),
    // "suffix": figma.boolean('Suffix?'),
    // "prefix": figma.boolean('Prefix?'),
    // "prefix": figma.string('Prefix'),
    // "suffix": figma.string('Suffix'),
    // "optional": figma.boolean('Optional?'),
    // "valueType": figma.enum('Value type', {
    //   "Empty": "empty",
    //   "Placeholder": "placeholder",
    //   "Filled": "filled"
    // }),
    // "labelVariant": figma.enum('Label variant', {
    //   "Body": "body",
    //   "Heading": "heading"
    // })
  },
  example: props => (
    <Input
      disabled={props.disabled}
      readonly={props.readonly}
      focused={props.focused}
      placeholder={props.placeholder}
      focusable={props.focusable}
    />
  ),
});
