import React from "react"
import { ListActionLink } from "./ListActionLink"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ListActionLink,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=9661%3A5128",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "actionHeading": figma.string('Action heading'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Active": "active",
      //   "Disabled": "disabled",
      //   "Loading": "loading"
      // })
    },
    example: (props) => <ListActionLink />,
  },
)
