import figma from '@figma/code-connect';
import React from 'react';
import { List } from './List';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(List, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2437%3A621', {
  props: {
    // No matching props could be found for these Figma properties:
    // "sectionHeader": figma.boolean('Section header?'),
    // "listAction": figma.boolean('List action?'),
    // "container": figma.enum('Container', {
    //   "None": "none",
    //   "Subtle Warm White": "subtle-warm-white",
    //   "Emphasis Warm White": "emphasis-warm-white",
    //   "Subtle White": "subtle-white",
    //   "Emphasis White": "emphasis-white"
    // })
  },
  example: props => <List variant={null} colorScheme={null} />,
});
