import React from "react"
import { ListItem } from "./ListItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ListItem,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2421%3A1628",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "listHeading": figma.string('List heading'),
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "customContent": figma.instance('Custom content'),
      // "badge": figma.boolean('Badge?'),
      // "leadingContent": figma.boolean('Leading content?'),
      // "trailingContent": figma.boolean('Trailing Content?'),
      // "numericalValue": figma.boolean('Numerical value?'),
      // "numericalValue": figma.string('Numerical value'),
      // "variant": figma.enum('Variant', {
      //   "Default": "default",
      //   "Custom": "custom"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Active": "active",
      //   "Disabled": "disabled",
      //   "Loading": "loading"
      // }),
      // "paddingNone": figma.boolean('Padding None?')
    },
    example: (props) => <ListItem />,
  },
)
