import React from "react"
import SelectOption from "./SelectOption"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectOption,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=4340%3A1252",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      selected: figma.boolean("Selected?"),
      disabled: figma.enum("State", {
        Active: true,
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "icon": figma.boolean('Icon?'),
      // "icon20": figma.instance('Icon-20')
    },
    example: (props) => (
      <SelectOption
        label={props.label}
        value={/* TODO */}
        selected={props.selected}
        disabled={props.disabled}
      />
    ),
  },
)
