import React from "react"
import Select from "./Select"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3224%3A995",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      placeholder: figma.string("Label"),
      disabled: figma.enum("Variant", {
        Disabled: true,
      }),
      emptyText: figma.string("Helper text"),
      readonly: figma.enum("Variant", {
        "Read-only": true,
      }),
      collapsable: figma.boolean("Dropdown?"),
      focusable: figma.boolean("Focus?"),
      hasTVPreferredFocus: figma.boolean("Focus?"),
      "aria-disabled": figma.enum("Variant", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.string('Label'),
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "value": figma.string('Value'),
      // "dropdown": figma.boolean('Dropdown?'),
      // "optional": figma.boolean('Optional?'),
      // "valueType": figma.enum('Value type', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Selected": "selected"
      // })
    },
    example: (props) => (
      <Select
        label={props.label}
        placeholder={props.placeholder}
        disabled={props.disabled}
        emptyText={props.emptyText}
        readonly={props.readonly}
        collapsable={props.collapsable}
        focusable={props.focusable}
        hasTVPreferredFocus={props.hasTVPreferredFocus}
        aria-disabled={props.aria - disabled}
      />
    ),
  },
)
