import React from "react"
import List from "./List"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  List,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2437%3A621",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      container: figma.enum("Container", {
        None: "none",
        "Subtle White": "subtleWhite",
        "Emphasis White": "emphasisWhite",
        "Subtle Warm White": "subtleWarmWhite",
        "Emphasis Warm White": "emphasisWarmWhite",
      }),
      // No matching props could be found for these Figma properties:
      // "sectionHeader": figma.boolean('Section header?'),
      // "listAction": figma.boolean('List action?')
    },
    example: (props) => <List container={props.container} />,
  },
)
