version: 2
registries:
  npm-uw:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}

updates:
  # ignore security updates for docs etc.
  - package-ecosystem: 'npm'
    directory: '/apps'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'

  - package-ecosystem: 'npm'
    directory: '/packages'
    registries:
      - npm-uw
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 4
    pull-request-branch-name:
      separator: '-'
    groups:
      all:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'next'

  - package-ecosystem: 'docker'
    directory: '/apps/server-storybook-docs'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
