packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  react: 19.1.0
  react-dom: 19.1.0
  zod-validation-error: ^4.0.2
peerDependencyRules:
  allowedVersions:
    eslint-plugin-react>eslint: '10'
    eslint-plugin-jsx-a11y>eslint: '10'
publicHoistPattern:
  - 'expo-modules-core'
patchedDependencies:
  react-native-worklets@0.5.1: patches/react-native-worklets@0.5.1.patch
allowUnusedPatches: true
nodeLinker: hoisted
allowBuilds:
  '@bundled-es-modules/glob': true
  '@swc/core': true
  dtrace-provider: true
  esbuild: true
  react-native-nitro-modules: true
  sharp: true
  style-dictionary: true
  unrs-resolver: true
supportedArchitectures:
  os:
    - current
  cpu:
    - current
verifyDepsBeforeRun: warn
minimumReleaseAgeExclude:
  - '@changesets/cli@2.31.1'
