import React from "react"
import { ToggleButtonCard } from "./ToggleButtonCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToggleButtonCard,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=4842%3A1131",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      name: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Active": "active",
      //   "Focus": "focus"
      // }),
      // "selected": figma.boolean('Selected?')
    },
    example: (props) => (
      <ToggleButtonCard
        label={props.label}
        aria-labelledby={/* TODO */}
        name={props.name}
        value={/* TODO */}
      />
    ),
  },
)
