import React from "react"
import { HighlightBannerContent } from "./HighlightBannerContent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  HighlightBannerContent,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=8306%3A4665",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Heading color", {
        Broadband: "brand",
      }),
      backgroundColor: figma.enum("Heading color", {
        Broadband: "brand",
      }),
      // No matching props could be found for these Figma properties:
      // "image": figma.boolean('Image?'),
      // "description": figma.string('Description'),
      // "heading": figma.string('Heading'),
      // "link": figma.boolean('Link?'),
      // "button": figma.boolean('Button?'),
      // "image": figma.instance('Image')
    },
    example: (props) => (
      <HighlightBannerContent
        as={/* TODO */}
        color={props.color}
        backgroundColor={props.backgroundColor}
      />
    ),
  },
)
