import React from "react"
import Carousel from "./Carousel"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Carousel,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=5191%3A3220",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      inverted: figma.boolean("Inverted?"),
      // No matching props could be found for these Figma properties:
      // "arrows": figma.boolean('Arrows?')
    },
    example: (props) => (
      <Carousel width={/* TODO */} inverted={props.inverted} />
    ),
  },
)
