import React from "react"
import Alert from "./Alert"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3288%3A4656",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      colorScheme: figma.enum("Color Scheme", {
        Info: "info",
        Positive: "positive",
        Warning: "warning",
        Danger: "danger",
      }),
      // No matching props could be found for these Figma properties:
      // "iconButton": figma.boolean('Icon button?'),
      // "close": figma.boolean('Close?'),
      // "link": figma.boolean('Link?'),
      // "title": figma.string('Title'),
      // "title": figma.boolean('Title?'),
      // "text": figma.string('Text')
    },
    example: (props) => <Alert colorScheme={props.colorScheme} />,
  },
)
