import React from "react"
import ExpandableCard from "./ExpandableCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ExpandableCard,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7222%3A5935",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      expanded: figma.boolean("Expand?"),
      heading: figma.string("Heading"),
      helperText: figma.string("Helper text"),
      expandedContent: figma.enum("Expand?", {
        False: false,
        True: true,
      }),
      disabled: figma.enum("State", {
        Active: true,
      }),
      collapsable: figma.boolean("Expand?"),
      focusable: figma.enum("State", {
        Focus: true,
      }),
      // No matching props could be found for these Figma properties:
      // "customContent": figma.instance('Custom content'),
      // "heading": figma.string('Heading'),
      // "helperText": figma.string('Helper text'),
      // "helperText": figma.boolean('Helper text?'),
      // "numericalValue": figma.boolean('Numerical value?'),
      // "numericalValue": figma.string('Numerical value'),
      // "leadingContent": figma.boolean('Leading content?'),
      // "badge": figma.boolean('Badge?')
    },
    example: (props) => (
      <ExpandableCard
        expanded={props.expanded}
        heading={props.heading}
        helperText={props.helperText}
        expandedContent={props.expandedContent}
        disabled={props.disabled}
        collapsable={props.collapsable}
        focusable={props.focusable}
      />
    ),
  },
)
