import React from "react"
import { CardBannerContent } from "./CardBannerContent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardBannerContent,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=8294%3A3905",
  {
    props: {},
    example: (props) => <CardBannerContent heading={/* TODO */} />,
  },
)
