import React from "react"
import { Card } from "./Card"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2160%3A11",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Emphasis: "emphasis",
        Subtle: "subtle",
      }),
      colorScheme: figma.enum("Color Scheme", {
        Mobile: "mobile",
        "Neutral Strong": "neutralStrong",
        "Neutral Subtle": "neutralSubtle",
        Brand: "brand",
        Energy: "energy",
        Broadband: "broadband",
        Insurance: "insurance",
        Cashback: "cashback",
        Pig: "pig",
        Highlight: "highlight",
      }),
      paddingNone: figma.boolean("Padding None?"),
      // No matching props could be found for these Figma properties:
      // "content": figma.instance('Content')
    },
    example: (props) => (
      <Card
        variant={props.variant}
        colorScheme={props.colorScheme}
        paddingNone={props.paddingNone}
      />
    ),
  },
)
