import figma from "@figma/code-connect"
import { TableCell } from "./TableCell"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TableCell,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6403%3A8140",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "variant": figma.enum('Variant', {
      //   "Text": "text",
      //   "Badge": "badge",
      //   "Link": "link",
      //   "Button": "button",
      //   "Roundel": "roundel",
      //   "Custom content": "custom-content"
      // })
    },
    example: (props) => <TableCell />,
  },
)
