import React from "react"
import { Table } from "./Table"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Table,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6403%3A17515",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "pagination": figma.boolean('Pagination?'),
      // "scrollBar": figma.boolean('Scroll bar?'),
      // "container": figma.enum('Container', {
      //   "Subtle": "subtle",
      //   "Emphasis": "emphasis",
      //   "None": "none"
      // }),
      // "device": figma.enum('Device', {
      //   "Desktop": "desktop",
      //   "Mobile & Tablet": "mobile---tablet"
      // })
    },
    example: (props) => <Table />,
  },
)
