import figma from '@figma/code-connect';
import Switch from './Switch';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(Switch, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3044%3A243', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.enum('State', {
      Disabled: true,
    }),
    'aria-disabled': figma.enum('State', {
      Disabled: true,
    }),
    focusable: figma.enum('State', {
      Focus: true,
    }),
    checked: figma.boolean('Checked?'),
    size: figma.enum('Size', {
      'MD-32': 'medium',
      'SM-24': 'small',
    }),
  },
  example: props => (
    <Switch
      value={props.checked}
      disabled={props.disabled}
      focusable={props.focusable}
      size={props.size}
    />
  ),
});
