import figma from '@figma/code-connect';
import React from 'react';
import { RadioTile } from './RadioTile';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioTile,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3138%3A13222',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.boolean('Checked?'),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "label": figma.string('Label'),
      // "image": figma.boolean('Image?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Focus": "focus"
      // })
    },
    example: props => <RadioTile label={null} value={null} checked={props.checked} />,
  }
);
