import figma from '@figma/code-connect';
import ListAction from './ListAction';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ListAction,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=9661%3A5128',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      heading: figma.string('Action heading'),
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      'aria-disabled': figma.enum('State', {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "actionHeading": figma.string('Action heading')
    },
    example: props => <ListAction heading={props.heading} disabled={props.disabled} />,
  }
);
