import React from "react"
import Tabs from "./Tabs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tabs,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6464%3A8744",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "MD-56": "md",
        "LG-64": "lg",
      }),
      // No matching props could be found for these Figma properties:
      // "arrowLeft": figma.boolean('Arrow left?'),
      // "arrowRight": figma.boolean('Arrow right?'),
      // "condensed": figma.boolean('Condensed?')
    },
    example: (props) => <Tabs size={props.size} />,
  },
)
