import React from "react"
import { MenuItem } from "./MenuItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7247%3A5209",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "heading": figma.string('Heading'),
      // "description": figma.string('Description'),
      // "trailingContent": figma.boolean('Trailing content?'),
      // "numericalValue": figma.string('Numerical value'),
      // "numericalValue": figma.boolean('Numerical value?'),
      // "description": figma.boolean('Description?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid"
      // }),
      // "direction": figma.enum('Direction', {
      //   "Row": "row",
      //   "Column": "column"
      // })
    },
    example: (props) => <MenuItem />,
  },
)
