import React from "react"
import { PasswordInput } from "./PasswordInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PasswordInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2251%3A10106",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Label"),
      placeholder: figma.string("Label"),
      readOnly: figma.enum("State", {
        "Read-only": true,
      }),
      helperText: figma.string("Helper text"),
      validationText: figma.string("Validation"),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.string('Label'),
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "value": figma.string('Value'),
      // "password": figma.string('Password'),
      // "valueType": figma.enum('Value type', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Filled": "filled"
      // }),
      // "focus": figma.boolean('Focus?'),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // })
    },
    example: (props) => (
      <PasswordInput
        label={props.label}
        disabled={props.disabled}
        name={props.name}
        placeholder={props.placeholder}
        readOnly={props.readOnly}
        helperText={props.helperText}
        validationText={props.validationText}
      />
    ),
  },
)
