import React from "react"
import { Avatar } from "../components/Avatar/Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6790%3A14313",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "SM-32": "sm",
        "MD-48": "md",
      }),
      // No matching props could be found for these Figma properties:
      // "initials": figma.string('Initials'),
      // "image": figma.instance('Image'),
      // "variant": figma.enum('Variant', {
      //   "Image": "image",
      //   "Initials": "initials",
      //   "Icon": "icon"
      // })
    },
    example: (props) => <Avatar size={props.size} />,
  },
)
