import React from "react"
import { Breadcrumbs } from "../components/Breadcrumbs/Breadcrumbs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=9617%3A42123",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      inverted: figma.boolean("Inverted?"),
    },
    example: (props) => <Breadcrumbs inverted={props.inverted} />,
  },
)
