import React from "react"
import { CardActions } from "../components/CardActions/CardActions"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardActions,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=8154%3A4346",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "listHeading": figma.string('List heading'),
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "iconContainer": figma.boolean('Icon container?'),
      // "trailingIcon20": figma.instance('Trailing icon-20'),
      // "leadingIcon": figma.boolean('Leading Icon?'),
      // "leadingIcon24": figma.instance('Leading icon-24'),
      // "badgeRight": figma.boolean('Badge right?'),
      // "badgeBottom": figma.boolean('Badge bottom?'),
      // "badgeMiddle": figma.boolean('Badge middle?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Active": "active",
      //   "Disabled": "disabled",
      //   "Loading": "loading"
      // }),
      // "size": figma.enum('Size', {
      //   "Default": "default",
      //   "Large": "large"
      // })
    },
    example: (props) => <CardActions />,
  },
)
