import React from "react"
import { CurrencyInput } from "../components/CurrencyInput/CurrencyInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CurrencyInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2161%3A1336",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      name: figma.string("Label"),
      placeholder: figma.string("Label"),
      helperText: figma.string("Helper text"),
      validationText: figma.string("Validation"),
      // No matching props could be found for these Figma properties:
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "label": figma.string('Label'),
      // "value": figma.string('Value'),
      // "helperText": figma.boolean('Helper text?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid"
      // }),
      // "valueType": figma.enum('Value type', {
      //   "Placeholder": "placeholder",
      //   "Filled": "filled"
      // }),
      // "focus": figma.boolean('Focus?'),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // })
    },
    example: (props) => (
      <CurrencyInput
        label={props.label}
        name={props.name}
        placeholder={props.placeholder}
        helperText={props.helperText}
        validationText={props.validationText}
      />
    ),
  },
)
