import React from "react"
import { IconContainer } from "../components/IconContainer/IconContainer"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconContainer,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=5462%3A9728",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "SM-32": "sm",
        "MD-48": "md",
        "LG-64": "lg",
      }),
      variant: figma.enum("Variant", {
        Emphasis: "emphasis",
        Subtle: "subtle",
      }),
      colorScheme: figma.enum("Color", {
        Mobile: "mobile",
        Energy: "energy",
        Broadband: "broadband",
        Insurance: "insurance",
        Cashback: "cashback",
        Pig: "pig",
        Highlight: "highlight",
      }),
      // No matching props could be found for these Figma properties:
      // "icon20": figma.instance('Icon-20'),
      // "icon24": figma.instance('Icon-24'),
      // "radiusNone": figma.boolean('Radius None?')
    },
    example: (props) => (
      <IconContainer
        size={props.size}
        variant={props.variant}
        colorScheme={props.colorScheme}
      />
    ),
  },
)
