import figma from '@figma/code-connect';
import React from 'react';
import { IconButton } from '../components/IconButton/IconButton';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(IconButton, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=90%3A1455', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.enum('State', {
      Disabled: true,
    }),
    loading: figma.enum('State', {
      Loading: true,
    }),
    inverted: figma.boolean('Inverted?'),
    size: figma.enum('Size', {
      'SM-32': 'sm',
      'MD-48': 'md',
    }),
    // No matching props could be found for these Figma properties:
    // "icon24": figma.instance('Icon-24'),
    // "icon20": figma.instance('Icon-20'),
    // "variant": figma.enum('Variant', {
    //   "Emphasis": "emphasis",
    //   "Solid": "solid",
    //   "Outline": "outline",
    //   "Ghost": "ghost"
    // }),
    // "colorScheme": figma.enum('Color Scheme', {
    //   "Highlight": "highlight",
    //   "Functional": "functional",
    //   "Affirmative": "affirmative",
    //   "Destructive": "destructive"
    // })
  },
  example: props => (
    <IconButton
      disabled={props.disabled}
      loading={props.loading}
      inverted={props.inverted}
      label=''
      size={props.size}
    />
  ),
});
