import React from "react"
import { Menu } from "../components/Menu/Menu"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Menu,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3263%3A18832",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "heading": figma.string('Heading'),
      // "heading": figma.boolean('Heading?'),
      // "grabber": figma.boolean('Grabber?'),
      // "deviceType": figma.enum('Device type', {
      //   "Web": "web",
      //   "App": "app"
      // })
    },
    example: (props) => <Menu />,
  },
)
