import React from "react"
import { Modal } from "../components/Modal/Modal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6300%3A2825",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      heading: figma.string("Heading"),
      description: figma.string("Description"),
      fullScreen: figma.boolean("Full screen?"),
      image: figma.enum("Image?", {
        False: false,
        True: true,
      }),
      // No matching props could be found for these Figma properties:
      // "heading": figma.string('Heading'),
      // "description": figma.string('Description'),
      // "customContent": figma.boolean('Custom content?'),
      // "buttons": figma.boolean('Buttons?'),
      // "close": figma.boolean('Close?'),
      // "customContent": figma.instance('Custom content'),
      // "homeIndicator": figma.boolean('Home indicator?'),
      // "handle": figma.boolean('Handle?'),
      // "loadingHeading": figma.string('Loading heading'),
      // "deviceType": figma.enum('Device type', {
      //   "Desktop": "desktop",
      //   "Tablet": "tablet",
      //   "Mobile": "mobile"
      // }),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Loading": "loading"
      // })
    },
    example: (props) => (
      <Modal
        heading={props.heading}
        description={props.description}
        fullScreen={props.fullScreen}
        image={props.image}
      />
    ),
  },
)
