import figma from '@figma/code-connect';
import React from 'react';
import { Pagination } from '../components/Pagination/Pagination';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Pagination,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6416%3A5836',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      condensed: figma.boolean('Condensed?'),
      hideSkipButtons: figma.boolean('Skip?'),
      // No matching props could be found for these Figma properties:
      // "skip": figma.boolean('Skip?')
    },
    example: props => (
      <Pagination
        currentPage={1}
        onPageChange={() => console.log('on page change')}
        totalPages={5}
        condensed={props.condensed}
        hideSkipButtons={props.hideSkipButtons}
      />
    ),
  }
);
