import React from "react"
import { ProgressStepper } from "../components/ProgressStepper/ProgressStepper"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressStepper,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=10612%3A1860",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.string('Label'),
      // "helperText": figma.string('Helper text'),
      // "value": figma.string('Value'),
      // "validation": figma.string('Validation'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid"
      // }),
      // "focus": figma.boolean('Focus?'),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // })
    },
    example: (props) => <ProgressStepper />,
  },
)
