import figma from '@figma/code-connect';
import React from 'react';
import { ProgressBarCircular } from '../components/ProgressBarCircular/ProgressBarCircular';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBarCircular,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7863%3A3977',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      labelId: figma.string('Label'),
      colorScheme: figma.enum('Color Scheme', {
        Default: 'default',
        Success: 'success',
        Danger: 'danger',
      }),
      size: figma.enum('Size', {
        'SM-80': 'sm',
        'MD-140': 'md',
      }),
      label: figma.string('Label'),
      hideLabel: figma.boolean('Label?'),
      margin: figma.enum('Size', {
        'SM-80': '800',
        'MD-140': '400',
      }),
      marginTop: figma.enum('Size', {
        'SM-80': '800',
        'MD-140': '400',
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label?'),
      // "label": figma.string('Label'),
      // "progress": figma.enum('Progress', {
      //   "10%": "10-",
      //   "20%": "20-",
      //   "30%": "30-",
      //   "40%": "40-",
      //   "50%": "50-",
      //   "60%": "60-",
      //   "70%": "70-",
      //   "80%": "80-",
      //   "90%": "90-",
      //   "100%": "100-",
      //   "0%": "0-"
      // })
    },
    example: props => (
      <ProgressBarCircular
        valueText={null}
        labelId={props.labelId}
        colorScheme={props.colorScheme}
        size={props.size}
        value={null}
        label={props.label}
        hideLabel={props.hideLabel}
        margin={props.margin}
        marginTop={props.marginTop}
      />
    ),
  }
);
