import figma from '@figma/code-connect';
import React from 'react';
import { SelectItem } from '../components/SelectItem/SelectItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectItem,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3394%3A3663',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "selected": figma.boolean('Selected?')
    },
    example: props => <SelectItem value={null} disabled={props.disabled} />,
  }
);
