import React from "react"
import { Select } from "../components/Select/Select"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3224%3A995",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("Variant", {
        Disabled: true,
      }),
      name: figma.string("Label"),
      value: figma.string("Value"),
      defaultValue: figma.string("Value"),
      label: figma.string("Label"),
      helperText: figma.string("Helper text"),
      validationText: figma.string("Validation"),
      placeholder: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.string('Label'),
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "value": figma.string('Value'),
      // "dropdown": figma.boolean('Dropdown?'),
      // "optional": figma.boolean('Optional?'),
      // "valueType": figma.enum('Value type', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Selected": "selected"
      // }),
      // "focus": figma.boolean('Focus?')
    },
    example: (props) => (
      <Select
        disabled={props.disabled}
        name={props.name}
        value={props.value}
        defaultValue={props.defaultValue}
        label={props.label}
        helperText={props.helperText}
        validationText={props.validationText}
        placeholder={props.placeholder}
      />
    ),
  },
)
