import React from "react"
import { Spinner } from "../components/Spinner/Spinner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Spinner,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=61%3A195",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "XS-20": "xs",
        "SM-24": "sm",
        "MD-32": "md",
        "LG-44": "lg",
      }),
      margin: figma.enum("Size", {
        "XS-20": "250",
      }),
      marginTop: figma.enum("Size", {
        "XS-20": "250",
      }),
    },
    example: (props) => (
      <Spinner
        size={props.size}
        margin={props.margin}
        marginTop={props.marginTop}
      />
    ),
  },
)
