import React from "react"
import { Switch } from "../components/Switch/Switch"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3044%3A243",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        "SM-24": "sm",
        "MD-32": "md",
      }),
      checked: figma.boolean("Checked?"),
      defaultChecked: figma.boolean("Checked?"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
    },
    example: (props) => (
      <Switch
        size={props.size}
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        disabled={props.disabled}
      />
    ),
  },
)
