import React from "react"
import { TableHeaderCell } from "./TableHeaderCell"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TableHeaderCell,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6414%3A6728",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "sort": figma.boolean('Sort?'),
      // "variant": figma.enum('Variant', {
      //   "Text": "text",
      //   "Blank": "blank"
      // }),
      // "color": figma.enum('Color', {
      //   "Purple": "purple",
      //   "White": "white"
      // })
    },
    example: (props) => <TableHeaderCell />,
  },
)
