import React from "react"
import { SearchInput } from "./SearchInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SearchInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2161%3A1311",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      loading: figma.enum("State", {
        Loading: true,
      }),
      label: figma.string("Label"),
      name: figma.string("Label"),
      placeholder: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "value": figma.string('Value'),
      // "label": figma.string('Label'),
      // "helperText": figma.string('Helper text'),
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.boolean('Label?'),
      // "focus": figma.boolean('Focus?')
    },
    example: (props) => (
      <SearchInput
        loading={props.loading}
        label={props.label}
        name={props.name}
        placeholder={props.placeholder}
      />
    ),
  },
)
