export const datePicker = {
  backgroundColor: 'var(--h-date-picker-background-color)',
  borderColor: 'var(--h-date-picker-border-color)',
  borderColorInvalid: 'var(--h-date-picker-border-color-invalid)',
  borderColorReadOnly: 'var(--h-date-picker-border-color-read-only)',
  borderColorValid: 'var(--h-date-picker-border-color-valid)',
  borderRadius: 'var(--h-date-picker-border-radius)',
  borderWidth: 'var(--h-date-picker-border-width)',
  borderWidthFocused: 'var(--h-date-picker-border-width-focused)',
  calendar: {
    backgroundColor: 'var(--h-date-picker-calendar-background-color)',
    borderColor: 'var(--h-date-picker-calendar-border-color)',
    borderRadius: 'var(--h-date-picker-calendar-border-radius)',
    borderWidth: 'var(--h-date-picker-calendar-border-width)',
    columnGap: 'var(--h-date-picker-calendar-column-gap)',
    footer: {
      gap: 'var(--h-date-picker-calendar-footer-gap)',
    },
    gap: 'var(--h-date-picker-calendar-gap)',
    header: {
      controlGap: 'var(--h-date-picker-calendar-header-control-gap)',
      dateGap: 'var(--h-date-picker-calendar-header-date-gap)',
    },
    item: {
      backgroundColorActive: 'var(--h-date-picker-calendar-item-background-color-active)',
      backgroundColorHover: 'var(--h-date-picker-calendar-item-background-color-hover)',
      backgroundColorRange: 'var(--h-date-picker-calendar-item-background-color-range)',
      backgroundColorSelected: 'var(--h-date-picker-calendar-item-background-color-selected)',
      borderRadius: 'var(--h-date-picker-calendar-item-border-radius)',
      roundelBackgroundColor: 'var(--h-date-picker-calendar-item-roundel-background-color)',
      roundelBackgroundColorInverted:
        'var(--h-date-picker-calendar-item-roundel-background-color-inverted)',
      roundelHeight: 'var(--h-date-picker-calendar-item-roundel-height)',
      roundelWidth: 'var(--h-date-picker-calendar-item-roundel-width)',
    },
    maxWidth: 'var(--h-date-picker-calendar-max-width)',
    minWidth: 'var(--h-date-picker-calendar-min-width)',
    padding: 'var(--h-date-picker-calendar-padding)',
    rowGap: 'var(--h-date-picker-calendar-row-gap)',
  },
  gap: 'var(--h-date-picker-gap)',
  gapContainer: 'var(--h-date-picker-gap-container)',
  header: {
    controlGap2: 'var(--h-date-picker-header-control-gap-2)',
  },
  height: 'var(--h-date-picker-height)',
  maxWidth: 'var(--h-date-picker-max-width)',
  minWidth: 'var(--h-date-picker-min-width)',
  paddingHorizontal: 'var(--h-date-picker-padding-horizontal)',
  paddingVertical: 'var(--h-date-picker-padding-vertical)',
};
