export const font = {
  family: {
    body: 'var(--h-font-family-body)',
    detail: 'var(--h-font-family-detail)',
    heading: 'var(--h-font-family-heading)',
  },
  size: {
    50: 'var(--h-font-size-50)',
    75: 'var(--h-font-size-75)',
    90: 'var(--h-font-size-90)',
    100: 'var(--h-font-size-100)',
    150: 'var(--h-font-size-150)',
    200: 'var(--h-font-size-200)',
    300: 'var(--h-font-size-300)',
    400: 'var(--h-font-size-400)',
    500: 'var(--h-font-size-500)',
    550: 'var(--h-font-size-550)',
    600: 'var(--h-font-size-600)',
    700: 'var(--h-font-size-700)',
    800: 'var(--h-font-size-800)',
    900: 'var(--h-font-size-900)',
    1000: 'var(--h-font-size-1000)',
  },
  weight: {
    bold: 'var(--h-font-weight-bold)',
    heavy: 'var(--h-font-weight-heavy)',
    medium: 'var(--h-font-weight-medium)',
    regular: 'var(--h-font-weight-regular)',
    semibold: 'var(--h-font-weight-semibold)',
  },
};
