export const select = {
  backgroundColor: 'var(--h-select-background-color)',
  borderColor: 'var(--h-select-border-color)',
  borderColorInvalid: 'var(--h-select-border-color-invalid)',
  borderColorReadOnly: 'var(--h-select-border-color-read-only)',
  borderColorValid: 'var(--h-select-border-color-valid)',
  borderRadius: 'var(--h-select-border-radius)',
  borderWidth: 'var(--h-select-border-width)',
  borderWidthFocused: 'var(--h-select-border-width-focused)',
  dropdown: {
    backgroundColor: 'var(--h-select-dropdown-background-color)',
    borderColor: 'var(--h-select-dropdown-border-color)',
    borderWidth: 'var(--h-select-dropdown-border-width)',
    gap: 'var(--h-select-dropdown-gap)',
    gapContent: 'var(--h-select-dropdown-gap-content)',
    item: {
      backgroundColorActive: 'var(--h-select-dropdown-item-background-color-active)',
      backgroundColorHover: 'var(--h-select-dropdown-item-background-color-hover)',
      borderRadius: 'var(--h-select-dropdown-item-border-radius)',
      foregroundColor: 'var(--h-select-dropdown-item-foreground-color)',
      gap: 'var(--h-select-dropdown-item-gap)',
      padding: 'var(--h-select-dropdown-item-padding)',
    },
    padding: 'var(--h-select-dropdown-padding)',
  },
  gap: 'var(--h-select-gap)',
  gapContainer: 'var(--h-select-gap-container)',
  height: 'var(--h-select-height)',
  maxWidth: 'var(--h-select-max-width)',
  minWidth: 'var(--h-select-min-width)',
  paddingHorizontal: 'var(--h-select-padding-horizontal)',
  paddingVertical: 'var(--h-select-padding-vertical)',
  validation: {
    gap: 'var(--h-select-validation-gap)',
  },
};
