export const space = {
  0: 'var(--h-space-0)',
  25: 'var(--h-space-25)',
  50: 'var(--h-space-50)',
  75: 'var(--h-space-75)',
  100: 'var(--h-space-100)',
  150: 'var(--h-space-150)',
  175: 'var(--h-space-175)',
  200: 'var(--h-space-200)',
  250: 'var(--h-space-250)',
  300: 'var(--h-space-300)',
  350: 'var(--h-space-350)',
  400: 'var(--h-space-400)',
  500: 'var(--h-space-500)',
  600: 'var(--h-space-600)',
  700: 'var(--h-space-700)',
  800: 'var(--h-space-800)',
  900: 'var(--h-space-900)',
  1000: 'var(--h-space-1000)',
  spacing: {
    '2xl': {
      desktop: 'var(--h-spacing-2xl-desktop)',
      mobile: 'var(--h-spacing-2xl-mobile)',
      tablet: 'var(--h-spacing-2xl-tablet)',
    },
    '2xs': {
      desktop: 'var(--h-spacing-2xs-desktop)',
      mobile: 'var(--h-spacing-2xs-mobile)',
      tablet: 'var(--h-spacing-2xs-tablet)',
    },
    lg: {
      desktop: 'var(--h-spacing-lg-desktop)',
      mobile: 'var(--h-spacing-lg-mobile)',
      tablet: 'var(--h-spacing-lg-tablet)',
    },
    md: {
      desktop: 'var(--h-spacing-md-desktop)',
      mobile: 'var(--h-spacing-md-mobile)',
      tablet: 'var(--h-spacing-md-tablet)',
    },
    none: {
      desktop: 'var(--h-spacing-none-desktop)',
      mobile: 'var(--h-spacing-none-mobile)',
      tablet: 'var(--h-spacing-none-tablet)',
    },
    sm: {
      desktop: 'var(--h-spacing-sm-desktop)',
      mobile: 'var(--h-spacing-sm-mobile)',
      tablet: 'var(--h-spacing-sm-tablet)',
    },
    xl: {
      desktop: 'var(--h-spacing-xl-desktop)',
      mobile: 'var(--h-spacing-xl-mobile)',
      tablet: 'var(--h-spacing-xl-tablet)',
    },
    xs: {
      desktop: 'var(--h-spacing-xs-desktop)',
      mobile: 'var(--h-spacing-xs-mobile)',
      tablet: 'var(--h-spacing-xs-tablet)',
    },
  },
};
