import Head from 'next/head';
import '@utilitywarehouse/hearth-fonts';
import '@utilitywarehouse/hearth-react/styles.css';
import {
  Button,
  Flex,
  Box as HearthBox,
  Link,
  Modal,
  ModalRoot,
  ModalTrigger,
  ModalFooter,
  ModalClose,
  Box,
  Breadcrumbs,
  BreadcrumbItem,
  List,
  ListItem,
  ListItemLink,
  Combobox,
} from '@utilitywarehouse/hearth-react';
// eslint-disable-next-line import/no-unresolved
import { StyledBox } from '@/components/StyledBox';
import { space, color, components, semantic } from '@utilitywarehouse/hearth-tokens/browser';
import NextLink from 'next/link';
import NextImage from 'next/image';
import SpotHelpLight from '@utilitywarehouse/hearth-svg-assets/lib/spot-help-light.svg';
import Lottie from 'lottie-react';
import { useEffect, useState } from 'react';
import SpotProcessCompleteFunctional from '@utilitywarehouse/hearth-json-assets/lib/spot-process-complete-functional.json';

export default function Home() {
  const { container } = components;

  const [animationData, setAnimationData] = useState(null);

  useEffect(() => {
    // Fetch the JSON from your CDN
    fetch(
      'https://cdn.bfldr.com/YUL5XOTG/at/9hqmq4rx3m2ff2frr3psmx5/Spot_Process-complete_Functional.json'
    )
      .then(res => res.json())
      .then(data => setAnimationData(data))
      .catch(err => console.error('Error loading animation:', err));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HearthBox padding="200">Hearth</HearthBox>
      <Breadcrumbs margin="400">
        <BreadcrumbItem asChild>
          <NextLink href="/one">One</NextLink>
        </BreadcrumbItem>
        <BreadcrumbItem asChild>
          <NextLink href="/two">Two</NextLink>
        </BreadcrumbItem>
        <BreadcrumbItem asChild>
          <NextLink href="/three">Three</NextLink>
        </BreadcrumbItem>
        <BreadcrumbItem currentPage>Home</BreadcrumbItem>
      </Breadcrumbs>
      <List>
        <ListItem>
          <ListItemLink heading="Page One" asChild>
            <NextLink href="/one" />
          </ListItemLink>
        </ListItem>
        <ListItem>
          <ListItemLink heading="Page Two" asChild>
            <NextLink href="/two" />
          </ListItemLink>
        </ListItem>
        <ListItem>
          <ListItemLink heading="Page Three" asChild>
            <NextLink href="/three" />
          </ListItemLink>
        </ListItem>
      </List>
      <StyledBox sx={{ border: '1px solid red', padding: '32px', display: 'flex' }}>
        Hearth styled with sx
      </StyledBox>
      <Flex padding="200" gap="300">
        <Button asChild onClick={() => console.log('Hearth React Button + Next.js')}>
          <NextLink href="https://nextjs.org/">Hearth React + Next.js</NextLink>
        </Button>
        <Link asChild>
          <NextLink
            href="https://nextjs.org/"
            onClick={() => console.log('Hearth React Link + Next.js')}
          >
            Hearth React + Next.js
          </NextLink>
        </Link>
      </Flex>
      <HearthBox>
        <HearthBox
          padding="200"
          backgroundColor="primary"
          position="relative"
          style={{ zIndex: 10 }}
        >
          Element with a z-index
        </HearthBox>
        <ModalRoot>
          <ModalTrigger>
            <Button>Open dialog</Button>
          </ModalTrigger>
          <Modal heading="Dialog">
            <ModalFooter>
              <ModalClose>
                <Button>Cancel</Button>
              </ModalClose>
            </ModalFooter>
          </Modal>
        </ModalRoot>
      </HearthBox>
      <div>
        <h1>CSS Reset</h1>
        <p>Checking the tokens work with the CSS Reset package.</p>
        <button>button</button>
        <button data-disabled>button</button>
        <button aria-disabled>button</button>
        <ul>
          <li>dog</li>
          <li>cat</li>
          <li>horse</li>
        </ul>
        <ul role="list">
          <li>dog</li>
          <li>cat</li>
          <li>horse</li>
        </ul>
        <a href="#">link</a>
        <div style={{ width: '300px', textAlign: 'center' }}>
          <h1>The UK's cheapest energy supplier when you bundle</h1>
        </div>
      </div>
      <div className="visually-hidden">Visually Hidden</div>
      <div>
        <h1>Hearth Tokens</h1>
        <StyledBox
          sx={{
            padding: space[200],
            color: color.broadbandGreen[500],
          }}
        >
          Hearth Tokens
        </StyledBox>
      </div>
      <Box position="relative" inset="400" top="100">
        position
      </Box>
      <div className="breakpoint-demo">
        <div className="breakpoint-demo__label">Breakpoint demo</div>
        <p className="breakpoint-demo__description">
          Resize the viewport: this box changes colour at the Hearth custom media breakpoints
          (--h-tablet, --h-desktop, --h-wide).
        </p>
      </div>
      <Flex
        maxWidth={container.width}
        color={semantic.feedback.positive.foreground.subtle}
        backgroundColor={semantic.feedback.positive.surface.subtle}
        borderWidth="1"
        borderStyle="solid"
        borderRadius="lg"
        borderColor={semantic.feedback.positive.border}
        // paddingBottom={{ mobile: '100', tablet: 'var(--h-space-200)', desktop: '32px' }}
        // paddingBottom={components.container.paddingBottom}
        // margin={components.container.margin}
        {...container}
        justifyContent="center"
        textTransform="uppercase"
      >
        container
      </Flex>
      <Flex width="100%" padding="600" gap="400" backgroundColor="var(--h-surface-energy-subtle)">
        <Button size="md" variant="outline" colorScheme="functional" asChild>
          <NextLink href="/energy/faqs">Energy FAQs</NextLink>
        </Button>
        <Button size="md" variant="outline" colorScheme="functional" asChild>
          <a href="https://www.uw.co.uk/energy/faqs">Energy FAQs</a>
        </Button>
      </Flex>
      <Flex marginBottom="1000" width="100%" justifyContent="center">
        <Combobox label="Fruits" items={['apple', 'banana', 'orange']}></Combobox>
      </Flex>
      <NextImage src={SpotHelpLight} alt="" width={200} height={200} />
      <NextImage src={SpotHelpLight} alt="" width={200} height={200} unoptimized />
      <img src={SpotHelpLight.src} alt="" width={200} height={200} />
      <NextImage
        src="https://cdn.bfldr.com/YUL5XOTG/at/pjbtphjjxxhn2qfkfch44qcf/UW_WFH_Lounge_032025_356.jpg?auto=webp&format=jpg"
        alt=""
        height={300}
        width={200}
      />
      <div style={{ width: 300, height: 300 }}>
        <Lottie animationData={animationData} loop={true} />
      </div>
      <div style={{ width: 300, height: 300 }}>
        <Lottie animationData={SpotProcessCompleteFunctional} loop={true} />
      </div>
    </>
  );
}
