import Head from 'next/head';
import '@utilitywarehouse/hearth-fonts';
import '@utilitywarehouse/hearth-react/styles.css';
import {
  Button,
  Flex,
  Box as HearthBox,
  Link,
  Dialog,
  DialogRoot,
  DialogTrigger,
  DialogFooter,
  DialogClose,
} from '@utilitywarehouse/hearth-react';
import { StyledBox } from '@/components/StyledBox';
import { space, color } from '@utilitywarehouse/hearth-tokens/browser';
import NextLink from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HearthBox padding="200">Hearth</HearthBox>
      <StyledBox sx={{ border: '1px solid red', padding: '32px', display: 'flex' }}>
        Hearth styled with sx
      </StyledBox>

      <Flex padding="200" gap="300">
        <Button asChild onClick={() => console.log('Hearth React Button + Next.js')}>
          <NextLink href="https://uw-hearth-react.vercel.app/?path=/docs/components-button--docs">
            Hearth React + Next.js
          </NextLink>
        </Button>
        <Link asChild>
          <NextLink
            href="https://uw-hearth-react.vercel.app/?path=/docs/components-link--docs"
            onClick={() => console.log('Hearth React Link + Next.js')}
          >
            Hearth React + Next.js
          </NextLink>
        </Link>
      </Flex>

      <HearthBox>
        <HearthBox
          padding="200"
          backgroundColor="warmWhite50"
          position="relative"
          style={{ zIndex: 10 }}
        >
          Element with a z-index
        </HearthBox>
        <DialogRoot>
          <DialogTrigger>
            <Button>Open dialog</Button>
          </DialogTrigger>
          <Dialog heading="Dialog">
            <DialogFooter>
              <DialogClose>
                <Button>Cancel</Button>
              </DialogClose>
            </DialogFooter>
          </Dialog>
        </DialogRoot>
      </HearthBox>

      <div>
        <h1>CSS Reset</h1>
        <p>Checking the tokens work with the CSS Reset package.</p>
        <button>button</button>
        <button data-disabled>button</button>
        <button aria-disabled>button</button>
        <ul role="list">
          <li>dog</li>
          <li>cat</li>
          <li>horse</li>
        </ul>
        <a href="#">link</a>
        <div style={{ width: '300px', textAlign: 'center' }}>
          <h1>The UK's cheapest energy supplier when you bundle</h1>
        </div>
      </div>
      <div className="visually-hidden">Visually Hidden</div>
      <div>
        <h1>Hearth Tokens</h1>
        <StyledBox
          sx={{
            padding: space[200],
            color: color.broadbandGreen,
          }}
        >
          Hearth Tokens
        </StyledBox>
      </div>
    </>
  );
}
