import Head from 'next/head';
import '@utilitywarehouse/hearth-fonts';
import '@utilitywarehouse/hearth-react/styles.css';
import {
  Button,
  Flex,
  Box as HearthBox,
  Link,
  Modal,
  ModalRoot,
  ModalTrigger,
  ModalFooter,
  ModalClose,
  Box,
} from '@utilitywarehouse/hearth-react';
import { StyledBox } from '@/components/StyledBox';
import { space, color, components, semantic } from '@utilitywarehouse/hearth-tokens/browser';
import NextLink from 'next/link';

export default function Home() {
  const { container } = components;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HearthBox padding="200">Hearth</HearthBox>
      <StyledBox sx={{ border: '1px solid red', padding: '32px', display: 'flex' }}>
        Hearth styled with sx
      </StyledBox>

      <Flex padding="200" gap="300">
        <Button asChild onClick={() => console.log('Hearth React Button + Next.js')}>
          <NextLink href="https://uw-hearth-react.vercel.app/?path=/docs/components-button--docs">
            Hearth React + Next.js
          </NextLink>
        </Button>
        <Link asChild>
          <NextLink
            href="https://uw-hearth-react.vercel.app/?path=/docs/components-link--docs"
            onClick={() => console.log('Hearth React Link + Next.js')}
          >
            Hearth React + Next.js
          </NextLink>
        </Link>
      </Flex>

      <HearthBox>
        <HearthBox
          padding="200"
          backgroundColor="warmWhite50"
          position="relative"
          style={{ zIndex: 10 }}
        >
          Element with a z-index
        </HearthBox>
        <ModalRoot>
          <ModalTrigger>
            <Button>Open dialog</Button>
          </ModalTrigger>
          <Modal heading="Dialog">
            <ModalFooter>
              <ModalClose>
                <Button>Cancel</Button>
              </ModalClose>
            </ModalFooter>
          </Modal>
        </ModalRoot>
      </HearthBox>

      <div>
        <h1>CSS Reset</h1>
        <p>Checking the tokens work with the CSS Reset package.</p>
        <button>button</button>
        <button data-disabled>button</button>
        <button aria-disabled>button</button>
        <ul>
          <li>dog</li>
          <li>cat</li>
          <li>horse</li>
        </ul>
        <ul role="list">
          <li>dog</li>
          <li>cat</li>
          <li>horse</li>
        </ul>
        <a href="#">link</a>
        <div style={{ width: '300px', textAlign: 'center' }}>
          <h1>The UK's cheapest energy supplier when you bundle</h1>
        </div>
      </div>
      <div className="visually-hidden">Visually Hidden</div>
      <div>
        <h1>Hearth Tokens</h1>
        <StyledBox
          sx={{
            padding: space[200],
            color: color.broadbandGreen[500],
          }}
        >
          Hearth Tokens
        </StyledBox>
      </div>

      <Box position="relative" inset="400" top="100">
        position
      </Box>

      <div className="breakpoint-demo">
        <div className="breakpoint-demo__label">Breakpoint demo</div>
        <p className="breakpoint-demo__description">
          Resize the viewport: this box changes colour at the Hearth custom media breakpoints
          (--h-tablet, --h-desktop, --h-wide).
        </p>
      </div>

      <Flex
        maxWidth={container.width}
        color={semantic.feedback.positive.foreground.subtle}
        backgroundColor={semantic.feedback.positive.surface.subtle}
        borderWidth="1"
        borderStyle="solid"
        borderRadius="lg"
        borderColor={semantic.feedback.positive.border}
        // paddingBottom={{ mobile: '100', tablet: 'var(--h-space-200)', desktop: '32px' }}
        // paddingBottom={components.container.paddingBottom}
        // margin={components.container.margin}
        {...container}
        justifyContent="center"
        textTransform="uppercase"
      >
        container
      </Flex>
    </>
  );
}
