import Head from 'next/head';
import '@utilitywarehouse/hearth-fonts';
import '@utilitywarehouse/hearth-react/styles.css';
import { Heading } from '@utilitywarehouse/hearth-react';

export default function One() {
  return (
    <>
      <Head>
        <title>One</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>One</Heading>
    </>
  );
}
