import React from "react"
import { Checkbox } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3087%3A7316",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.boolean("Checked?"),
      defaultChecked: figma.boolean("Checked?"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "helperText": figma.string('Helper text'),
      // "helperText": figma.boolean('Helper text?'),
      // "validationText": figma.string('Validation text'),
      // "image": figma.boolean('Image?')
    },
    example: (props) => (
      <Checkbox
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        disabled={props.disabled}
        name={props.name}
      />
    ),
  },
)
