import React from "react"
import ProgressStep from "./ProgressStep"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressStep,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6056%3A1987",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      status: figma.enum("State", {
        Complete: "complete",
        Active: "active",
        Incomplete: "incomplete",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "label": figma.boolean('Label?'),
      // "stepNumber": figma.string('Step number'),
      // "interactive": figma.boolean('Interactive?')
    },
    example: (props) => <ProgressStep id={/* TODO */} status={props.status} />,
  },
)
