import React from "react"
import BannerIllustration from "./BannerIllustration"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BannerIllustration,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=10145%3A4877",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "illustration": figma.instance('Illustration'),
      // "size": figma.enum('Size', {
      //   "XL-120": "xl-120",
      //   "LG-100": "lg-100",
      //   "MD-80": "md-80",
      //   "SM-60": "sm-60",
      //   "XS-40": "xs-40"
      // })
    },
    example: (props) => <BannerIllustration />,
  },
)
