import React from "react"
import SectionHeader from "./SectionHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SectionHeader,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=9092%3A3352",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "trailingContent": figma.boolean('Trailing content?'),
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "heading": figma.string('Heading'),
      // "badge": figma.boolean('Badge?'),
      // "state": figma.enum('State', {
      //   "Invalid": "invalid",
      //   "Default": "default"
      // })
    },
    example: (props) => <SectionHeader />,
  },
)
