import React from "react"
import CardAction from "./CardAction"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CardAction,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=8154%3A4346",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      loading: figma.enum("State", {
        Loading: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      "aria-disabled": figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "listHeading": figma.string('List heading'),
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "iconContainer": figma.boolean('Icon container?'),
      // "trailingIcon20": figma.instance('Trailing icon-20'),
      // "leadingIcon": figma.boolean('Leading Icon?'),
      // "leadingIcon24": figma.instance('Leading icon-24'),
      // "badgeRight": figma.boolean('Badge right?'),
      // "badgeBottom": figma.boolean('Badge bottom?'),
      // "badgeMiddle": figma.boolean('Badge middle?'),
      // "size": figma.enum('Size', {
      //   "Default": "default",
      //   "Large": "large"
      // })
    },
    example: (props) => (
      <CardAction
        loading={props.loading}
        disabled={props.disabled}
        aria-disabled={props.aria - disabled}
      />
    ),
  },
)
