import React from "react"
import AccordionItemRoot from "./AccordionItemRoot"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AccordionItemRoot,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3390%3A6160",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Active: true,
      }),
      title: figma.string("Title"),
      expanded: figma.boolean("Expand?"),
      triggerContent: figma.instance("Trigger custom content"),
      collapsable: figma.boolean("Expand?"),
      focusable: figma.enum("State", {
        Focus: true,
      }),
      // No matching props could be found for these Figma properties:
      // "customContent": figma.boolean('Custom content?'),
      // "title": figma.string('Title'),
      // "description": figma.string('Description'),
      // "customContent": figma.instance('Custom content'),
      // "triggerCustomContent": figma.instance('Trigger custom content'),
      // "triggerCustomContent": figma.boolean('Trigger custom content?')
    },
    example: (props) => (
      <AccordionItemRoot
        disabled={props.disabled}
        title={props.title}
        expanded={props.expanded}
        triggerContent={props.triggerContent}
        collapsable={props.collapsable}
        focusable={props.focusable}
      />
    ),
  },
)
