import React from "react"
import DatePickerInput from "./DatePickerInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DatePickerInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3917%3A7057",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("Variant", {
        Disabled: true,
      }),
      readonly: figma.enum("Variant", {
        "Read-only": true,
      }),
      focused: figma.boolean("Focus?"),
      placeholder: figma.string("Label"),
      autoFocus: figma.boolean("Focus?"),
      defaultValue: figma.string("Value"),
      readOnly: figma.enum("Variant", {
        "Read-only": true,
      }),
      focusable: figma.boolean("Focus?"),
      hasTVPreferredFocus: figma.boolean("Focus?"),
      "aria-disabled": figma.enum("Variant", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper  text?'),
      // "label": figma.string('Label'),
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "value": figma.string('Value'),
      // "icon": figma.boolean('Icon?'),
      // "calendar": figma.boolean('Calendar?'),
      // "valueType": figma.enum('Value type', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Filled": "filled"
      // })
    },
    example: (props) => (
      <DatePickerInput
        disabled={props.disabled}
        readonly={props.readonly}
        focused={props.focused}
        placeholder={props.placeholder}
        autoFocus={props.autoFocus}
        defaultValue={props.defaultValue}
        readOnly={props.readOnly}
        focusable={props.focusable}
        hasTVPreferredFocus={props.hasTVPreferredFocus}
        aria-disabled={props.aria - disabled}
      />
    ),
  },
)
