import React from "react"
import RadioImage from "./RadioImage"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  RadioImage,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7428%3A8535",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "customContent": figma.instance('Custom content'),
      // "variant": figma.enum('Variant', {
      //   "Bank logo": "bank-logo",
      //   "Custom": "custom"
      // })
    },
    example: (props) => <RadioImage />,
  },
)
