import React from "react"
import RadioTileRoot from "./RadioTileRoot"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  RadioTileRoot,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3138%3A13222",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "label": figma.string('Label'),
      // "image": figma.boolean('Image?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Focus": "focus"
      // }),
      // "checked": figma.boolean('Checked?')
    },
    example: (props) => <RadioTileRoot />,
  },
)
