import React from "react"
import RadioGroup from "./RadioGroup"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3138%3A13254",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Group label"),
      helperText: figma.string("Helper text"),
      invalidText: figma.string("Helper text"),
      validText: figma.string("Validation text"),
      direction: figma.enum("Direction", {
        Row: "row",
        Column: "column",
      }),
      // No matching props could be found for these Figma properties:
      // "groupLabel": figma.string('Group label'),
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "validationText": figma.string('Validation text'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid"
      // }),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // }),
      // "content": figma.enum('Content', {
      //   "Radio": "radio",
      //   "Radio Tile": "radio-tile"
      // })
    },
    example: (props) => (
      <RadioGroup
        label={props.label}
        helperText={props.helperText}
        invalidText={props.invalidText}
        validText={props.validText}
        direction={props.direction}
      />
    ),
  },
)
