import figma from '@figma/code-connect';
import UnstyledIconButton from './UnstyledIconButton';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  UnstyledIconButton,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2926%3A2430',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum('State', {
        Disabled: true,
      }),
      loading: figma.enum('State', {
        Loading: true,
      }),
      size: figma.enum('Size', {
        'SM-20': 'sm',
        'MD-24': 'md',
      }),
      inverted: figma.boolean('Inverted?'),
      'aria-disabled': figma.enum('State', {
        Disabled: true,
      }),
      focusable: figma.enum('State', {
        Focus: true,
      }),
      // No matching props could be found for these Figma properties:
      // "icon24": figma.instance('Icon-24'),
      // "icon20": figma.instance('Icon-20')
    },
    example: props => (
      <UnstyledIconButton
        disabled={props.disabled}
        icon={null}
        loading={props.loading}
        size={props.size}
        inverted={props.inverted}
        focusable={props.focusable}
      />
    ),
  }
);
