import React from "react"
import { CheckboxTile } from "./CheckboxTile"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxTile,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=4961%3A23797",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.boolean("Checked?"),
      defaultChecked: figma.boolean("Checked?"),
      name: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "helperText": figma.string('Helper text'),
      // "label": figma.string('Label'),
      // "image": figma.boolean('Image?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid",
      //   "Focus": "focus"
      // })
    },
    example: (props) => (
      <CheckboxTile
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        name={props.name}
      />
    ),
  },
)
