import React from "react"
import ListItemLeadingContent from "./ListItemLeadingContent"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ListItemLeadingContent,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=6732%3A5792",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "icon24": figma.instance('Icon-24'),
      // "variant": figma.enum('Variant', {
      //   "Icon": "icon",
      //   "Icon Container": "icon-container",
      //   "Avatar": "avatar",
      //   "Indicator": "indicator"
      // })
    },
    example: (props) => <ListItemLeadingContent />,
  },
)
