import figma from '@figma/code-connect';
import ListItem from './ListItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(ListItem, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2421%3A1628', {
  props: {
    // These props were automatically mapped based on your linked code:
    loading: figma.enum('State', {
      Loading: true,
    }),
    disabled: figma.enum('State', {
      Disabled: true,
    }),
    'aria-disabled': figma.enum('State', {
      Disabled: true,
    }),
    // No matching props could be found for these Figma properties:
    // "listHeading": figma.string('List heading'),
    // "helperText": figma.boolean('Helper text?'),
    // "helperText": figma.string('Helper text'),
    // "customContent": figma.instance('Custom content'),
    // "badge": figma.boolean('Badge?'),
    // "leadingContent": figma.boolean('Leading content?'),
    // "trailingContent": figma.boolean('Trailing Content?'),
    // "numericalValue": figma.boolean('Numerical value?'),
    // "numericalValue": figma.string('Numerical value'),
    // "variant": figma.enum('Variant', {
    //   "Default": "default",
    //   "Custom": "custom"
    // }),
    // "paddingNone": figma.boolean('Padding None?')
  },
  example: props => <ListItem loading={props.loading} disabled={props.disabled} />,
});
