import figma from '@figma/code-connect';
import { PillGroup } from './PillGroup';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PillGroup,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=4348%3A15988',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      wrap: figma.boolean('Wrap?'),
    },
    example: props => <PillGroup value={null} wrap={props.wrap} />,
  }
);
