import React from "react"
import { Pill } from "./Pill"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Pill,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=4348%3A15595",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      focusable: figma.enum("State", {
        Focus: true,
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "icon": figma.boolean('Icon?'),
      // "icon20": figma.instance('Icon-20'),
      // "selected": figma.boolean('Selected?')
    },
    example: (props) => (
      <Pill
        value={/* TODO */}
        label={props.label}
        focusable={props.focusable}
      />
    ),
  },
)
