import React from "react"
import Badge from "./Badge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=61%3A652",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        "Subtle - Default": "subtle",
        Emphasis: "emphasis",
        Outline: "outline",
      }),
      colorScheme: figma.enum("Color Scheme", {
        Info: "info",
        Positive: "positive",
        Danger: "danger",
        Warning: "warning",
        Functional: "functional",
        Energy: "energy",
        Broadband: "broadband",
        Mobile: "mobile",
        Insurance: "insurance",
        Cashback: "cashback",
        Pig: "pig",
        Highlight: "highlight",
      }),
      size: figma.enum("Size", {
        "SM-24": "sm",
        "MD-28": "md",
      }),
      flatBase: figma.boolean("Flat Base?"),
      // No matching props could be found for these Figma properties:
      // "icon": figma.boolean('Icon?'),
      // "icon20": figma.instance('Icon-20'),
      // "text": figma.string('Text')
    },
    example: (props) => (
      <Badge
        variant={props.variant}
        colorScheme={props.colorScheme}
        size={props.size}
        flatBase={props.flatBase}
      />
    ),
  },
)
