import React from "react"
import { ProgressBar } from "./ProgressBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=10562%3A2810",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "customContent": figma.boolean('Custom content?'),
      // "customContent": figma.instance('Custom content'),
      // "label": figma.string('Label'),
      // "helperText": figma.string('Helper text'),
      // "helperText": figma.boolean('Helper text?'),
      // "state": figma.enum('State', {
      //   "Complete": "complete",
      //   "Active": "active",
      //   "Incomplete": "incomplete"
      // }),
      // "variant": figma.enum('Variant', {
      //   "Start & Middle": "start---middle",
      //   "End": "end"
      // })
    },
    example: (props) => <ProgressBar value={/* TODO */} label={props.label} />,
  },
)
