import figma from '@figma/code-connect';
import React from 'react';
import { ProgressBarLinear } from './ProgressBarLinear';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBarLinear,
  'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=7849%3A5704',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      labelId: figma.string('Label'),
      colorScheme: figma.enum('Color Scheme', {
        Default: 'default',
        Success: 'success',
        Danger: 'danger',
      }),
      label: figma.string('Label'),
      hideLabel: figma.boolean('Label?'),
      marginTop: figma.enum('Progress', {
        '0%': '0',
        '50%': '50',
        '100%': '1000',
        '20%': '250',
        '30%': '350',
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label?'),
      // "label": figma.string('Label'),
      // "amountLabel": figma.string('Amount label')
    },
    example: props => (
      <ProgressBarLinear
        valueText={null}
        labelId={props.labelId}
        colorScheme={props.colorScheme}
        value={null}
        label={props.label}
        hideLabel={props.hideLabel}
        marginTop={props.marginTop}
      />
    ),
  }
);
