import React from "react"
import DatePickerCalendar from "./DatePickerCalendar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  DatePickerCalendar,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=3797%3A6383",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "grabber": figma.boolean('Grabber?'),
      // "header": figma.boolean('Header?'),
      // "footer": figma.boolean('Footer?'),
      // "deviceType": figma.enum('Device type', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // }),
      // "type": figma.enum('Type', {
      //   "Day": "day",
      //   "Month": "month",
      //   "Year": "year"
      // })
    },
    example: (props) => <DatePickerCalendar />,
  },
)
