import React from "react"
import { DateInput } from "./DateInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DateInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2277%3A14708",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hideDay: figma.boolean("Day?"),
      hideMonth: figma.boolean("Month?"),
      monthPlaceholder: figma.string("Month value"),
      yearPlaceholder: figma.string("Year value"),
      dayValue: figma.string("Day value"),
      monthValue: figma.string("Month value"),
      yearValue: figma.string("Year value"),
      defaultMonthValue: figma.string("Month value"),
      defaultYearValue: figma.string("Year value"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Label"),
      placeholder: figma.string("Label"),
      readOnly: figma.enum("State", {
        "Read-only": true,
      }),
      // No matching props could be found for these Figma properties:
      // "helperText": figma.boolean('Helper text?'),
      // "label": figma.string('Label'),
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "dayValue": figma.string('Day value'),
      // "day": figma.boolean('Day?'),
      // "month": figma.boolean('Month?'),
      // "monthValue": figma.string('Month value'),
      // "yearValue": figma.string('Year value'),
      // "optional": figma.boolean('Optional?'),
      // "valueType": figma.enum('Value type', {
      //   "Empty": "empty",
      //   "Placeholder": "placeholder",
      //   "Filled": "filled"
      // }),
      // "focus": figma.boolean('Focus?'),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // })
    },
    example: (props) => (
      <DateInput
        hideDay={props.hideDay}
        hideMonth={props.hideMonth}
        monthPlaceholder={props.monthPlaceholder}
        yearPlaceholder={props.yearPlaceholder}
        dayValue={props.dayValue}
        monthValue={props.monthValue}
        yearValue={props.yearValue}
        defaultMonthValue={props.defaultMonthValue}
        defaultYearValue={props.defaultYearValue}
        disabled={props.disabled}
        name={props.name}
        placeholder={props.placeholder}
        readOnly={props.readOnly}
      />
    ),
  },
)
