export const card = {
  borderRadius: 'var(--h-card-border-radius)',
  emphasis: {
    borderColor: 'var(--h-card-emphasis-border-color)',
    borderWidth: 'var(--h-card-emphasis-border-width)',
    broadbandGreenBackgroundColor: 'var(--h-card-emphasis-broadband-green-background-color)',
    cashbackLilacBackgroundColor: 'var(--h-card-emphasis-cashback-lilac-background-color)',
    energyBlueBackgroundColor: 'var(--h-card-emphasis-energy-blue-background-color)',
    insuranceOrangeBackgroundColor: 'var(--h-card-emphasis-insurance-orange-background-color)',
    mobileRoseBackgroundColor: 'var(--h-card-emphasis-mobile-rose-background-color)',
    purpleBackgroundColor: 'var(--h-card-emphasis-purple-background-color)',
  },
  selectable: {
    borderColor: 'var(--h-card-selectable-border-color)',
    borderColorSelected: 'var(--h-card-selectable-border-color-selected)',
    borderWidth: 'var(--h-card-selectable-border-width)',
    borderWidthSelected: 'var(--h-card-selectable-border-width-selected)',
    gap: 'var(--h-card-selectable-gap)',
  },
  subtle: {
    borderColor: 'var(--h-card-subtle-border-color)',
    borderWidth: 'var(--h-card-subtle-border-width)',
    broadbandGreenBackgroundColor: 'var(--h-card-subtle-broadband-green-background-color)',
    cashbackLilacBackgroundColor: 'var(--h-card-subtle-cashback-lilac-background-color)',
    energyBlueBackgroundColor: 'var(--h-card-subtle-energy-blue-background-color)',
    insuranceOrangeBackgroundColor: 'var(--h-card-subtle-insurance-orange-background-color)',
    mobileRoseBackgroundColor: 'var(--h-card-subtle-mobile-rose-background-color)',
    purpleBackgroundColor: 'var(--h-card-subtle-purple-background-color)',
    yellowBackgroundColor: 'var(--h-card-subtle-yellow-background-color)',
  },
  warmWhiteBackgroundColor: 'var(--h-card-warm-white-background-color)',
  whiteBackgroundColor: 'var(--h-card-white-background-color)',
} as const;
