export const input = {
  backgroundColor: 'var(--input-background-color)',
  borderColor: 'var(--input-border-color)',
  borderColorInvalid: 'var(--input-border-color-invalid)',
  borderColorReadOnly: 'var(--input-border-color-read-only)',
  borderColorValid: 'var(--input-border-color-valid)',
  borderRadius: 'var(--input-border-radius)',
  borderWidth: 'var(--input-border-width)',
  borderWidthFocused: 'var(--input-border-width-focused)',
  foregroundColorTextarea: 'var(--input-foreground-color-textarea)',
  gap: 'var(--input-gap)',
  gapCurrency: 'var(--input-gap-currency)',
  paddingHorizontal: 'var(--input-padding-horizontal)',
  paddingVertical: 'var(--input-padding-vertical)',
  placeholderColor: 'var(--input-placeholder-color)',
} as const;
