export const toggleButton = {
  backgroundColorActive: 'var(--h-toggle-button-background-color-active)',
  backgroundColorHover: 'var(--h-toggle-button-background-color-hover)',
  borderColor: 'var(--h-toggle-button-border-color)',
  borderRadius: 'var(--h-toggle-button-border-radius)',
  borderWidth: 'var(--h-toggle-button-border-width)',
  foregroundColor: 'var(--h-toggle-button-foreground-color)',
  gap: 'var(--h-toggle-button-gap)',
  height: 'var(--h-toggle-button-height)',
  minWidth: 'var(--h-toggle-button-min-width)',
  paddingHorizontal: 'var(--h-toggle-button-padding-horizontal)',
  paddingVertical: 'var(--h-toggle-button-padding-vertical)',
  selected: {
    backgroundColor: 'var(--h-toggle-button-selected-background-color)',
    backgroundColorActive: 'var(--h-toggle-button-selected-background-color-active)',
    backgroundColorHover: 'var(--h-toggle-button-selected-background-color-hover)',
    borderColor: 'var(--h-toggle-button-selected-border-color)',
    foregroundColor: 'var(--h-toggle-button-selected-foreground-color)',
  },
} as const;
