import React from "react"
import CurrencyInput from "./CurrencyInput"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CurrencyInput,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=2161%3A1336",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      focused: figma.boolean("Focus?"),
      placeholder: figma.string("Label"),
      autoFocus: figma.boolean("Focus?"),
      defaultValue: figma.string("Value"),
      value: figma.string("Value"),
      focusable: figma.boolean("Focus?"),
      hasTVPreferredFocus: figma.boolean("Focus?"),
      // No matching props could be found for these Figma properties:
      // "validation": figma.string('Validation'),
      // "helperText": figma.string('Helper text'),
      // "label": figma.string('Label'),
      // "value": figma.string('Value'),
      // "helperText": figma.boolean('Helper text?'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Invalid": "invalid"
      // }),
      // "valueType": figma.enum('Value type', {
      //   "Placeholder": "placeholder",
      //   "Filled": "filled"
      // }),
      // "labelVariant": figma.enum('Label variant', {
      //   "Body": "body",
      //   "Heading": "heading"
      // })
    },
    example: (props) => (
      <CurrencyInput
        focused={props.focused}
        placeholder={props.placeholder}
        autoFocus={props.autoFocus}
        defaultValue={props.defaultValue}
        value={props.value}
        focusable={props.focusable}
        hasTVPreferredFocus={props.hasTVPreferredFocus}
      />
    ),
  },
)
