import figma from '@figma/code-connect';
import IconButton from './IconButton';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(IconButton, 'https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=90%3A1455', {
  props: {
    // These props were automatically mapped based on your linked code:
    disabled: figma.enum('State', {
      Disabled: true,
    }),
    size: figma.enum('Size', {
      'SM-32': 'sm',
      'MD-48': 'md',
    }),
    loading: figma.enum('State', {
      Loading: true,
    }),
    focusable: figma.enum('State', {
      Focus: true,
    }),
    'aria-disabled': figma.enum('State', {
      Disabled: true,
    }),
    colorScheme: figma.enum('Color Scheme', {
      Affirmative: 'affirmative',
      Destructive: 'destructive',
    }),
    // No matching props could be found for these Figma properties:
    // "icon24": figma.instance('Icon-24'),
    // "icon20": figma.instance('Icon-20'),
    // "variant": figma.enum('Variant', {
    //   "Emphasis": "emphasis",
    //   "Solid": "solid",
    //   "Outline": "outline",
    //   "Ghost": "ghost"
    // }),
    // "inverted": figma.boolean('Inverted?')
  },
  example: props => (
    <IconButton
      disabled={props.disabled}
      size={props.size}
      icon={/* TODO */}
      loading={props.loading}
      focusable={props.focusable}
      colorScheme={props.colorScheme}
    />
  ),
});
