import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/6NKZXZhFSExXrcbBgc6zTR?node-id=90%3A432",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      loading: figma.enum("State", {
        Loading: true,
      }),
      inverted: figma.boolean("Inverted?"),
      size: figma.enum("Size", {
        "SM-32": "sm",
        "MD-48": "md",
      }),
      paddingNone: figma.boolean("Padding None?"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text'),
      // "showIconLeft": figma.boolean('Show icon left?'),
      // "showIconRight": figma.boolean('Show icon right?'),
      // "iconLeft20": figma.instance('Icon left-20'),
      // "iconRight20": figma.instance('Icon right-20'),
      // "ghostText": figma.string('Ghost Text'),
      // "variant": figma.enum('Variant', {
      //   "Emphasis": "emphasis",
      //   "Solid": "solid",
      //   "Outline": "outline",
      //   "Ghost": "ghost"
      // }),
      // "colorScheme": figma.enum('Color Scheme', {
      //   "Highlight": "highlight",
      //   "Functional": "functional",
      //   "Affirmative": "affirmative",
      //   "Destructive": "destructive"
      // })
    },
    example: (props) => (
      <Button
        disabled={props.disabled}
        loading={props.loading}
        inverted={props.inverted}
        size={props.size}
        paddingNone={props.paddingNone}
      />
    ),
  },
)
