name: Build Fonts
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/fonts/**'
      - 'apps/storybook-fonts/**'
  push:
    branches:
      - main
    paths:
      - 'packages/fonts/**'
      - 'apps/storybook-fonts/**'

permissions:
  contents: read

jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 9.15.2
      - name: 🏗 Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: 🏗 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}
      - name: 🏗 Build Fonts
        run: pnpm build:fonts
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
