name: Build Fonts
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/fonts/**'
      - 'apps/storybook-fonts/**'
  push:
    branches:
      - main
    paths:
      - 'packages/fonts/**'
      - 'apps/storybook-fonts/**'

permissions:
  contents: read

jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 10.28.2
      - name: 🏗 Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 🏗 Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}
      - name: 🏗 Build Fonts
        run: pnpm build:fonts
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
