name: Build Tokens

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'packages/tokens/raw/**'

permissions:
  contents: write

jobs:
  build_and_commit:
    name: Build and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 11.0.5
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          # Check out the PR's head branch with full history
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0 # Fetch all history for accurate merging
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}

      - name: Build Tokens
        working-directory: ./packages/tokens
        run: pnpm build:tokens

      - name: Add changeset
        run: |
          touch ./.changeset/${{ github.sha }}.md
          cat > ./.changeset/${{ github.sha }}.md << EOF
          ---
          "@utilitywarehouse/hearth-tokens": patch
          ---

          💅 [ENHANCEMENT]: Generate and build Hearth tokens

          EOF

      - name: Commit Built Files
        run: |
          git config --global user.name 'Hearth Design Systems Bot'
          git config --global user.email 'design-systems@uw.co.uk'
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Build design tokens output'
          fi

      - name: Push Changes
        run: |
          # Pull latest changes from the remote branch
          git pull origin ${{ github.event.pull_request.head.ref }}
          # Push your changes back to the PR's head branch
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
