name: Build React Native
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/react-native/**'
  push:
    branches:
      - main
    paths:
      - 'packages/react-native/**'

jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm 🛠️
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - name: Checkout code 📥
        uses: actions/checkout@v4
      - name: Setup Node.js environment 🌐
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install dependencies 📦
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_PUBLISH_TOKEN }}
      - name: Build React Native project 📱
        run: pnpm build:react-native
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
