name: Generate JSON Assets
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'json-assets-release'
        type: string
      type:
        description: |
          The semver type <major|minor|patch> to bump the packages.
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

env:
  CI: true

permissions:
  contents: read

jobs:
  generate:
    name: Generate JSON assets packages
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.8.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}

      - name: Create .env file
        run: |
          cat <<EOF > ./packages/json-assets/.env
          BRANDFOLDER_API_KEY=${{ secrets.BRANDFOLDER_API_KEY }}
          BRANDFOLDER_COLLECTION_ID=${{ secrets.BRANDFOLDER_COLLECTION_ID }}
          EOF

      - name: Generate JSON assets
        run: pnpm generate:json-assets:ci

      - name: Format files
        run: pnpm format

      - name: Set output variables
        id: vars
        run: |
          echo 'pr_body<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat updated-json-assets.md)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Add changeset
        run: |
          touch ./.changeset/${{ github.sha }}.md
          cat > ./.changeset/${{ github.sha }}.md << EOF
          ---
          "@utilitywarehouse/hearth-json-assets": ${{ inputs.type }}
          ---

          EOF
          cat updated-json-assets.md >> ./.changeset/${{ github.sha }}.md
          rm updated-json-assets.md

      - name: Open pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ inputs.branchName }}
          title: 'Generate updated JSON assets packages'
          commit-message: 'Generate updated JSON assets packages'
          delete-branch: true
          base: main
          body: ${{ steps.vars.outputs.pr_body }}
