name: Generate Icons
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'icons-release'
        type: string
      type:
        description: |
          The semver type <major|minor|patch> to bump the packages.
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

env:
  CI: true

permissions:
  contents: read

jobs:
  generate:
    name: Generate icons packages
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 9.15.2
      - name: 🏗 Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: 🏗 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_PUBLISH_TOKEN }}

      - name: create env file
        run: |
          touch ./packages/svg-icons/.env
          echo FIGMA_ACCESS_TOKEN=${{ secrets.FIGMA_ACCESS_TOKEN }} >> ./packages/svg-icons/.env

      - name: 🪄 Generate SVG icons
        run: pnpm generate:svg-icons

      - name: 🪄 Generate React & React Native icons
        run: pnpm generate:react

      - name: 🪄 Generate Storybook docs
        run: pnpm generate:storybook

      - name: Format files
        run: pnpm format

      - name: Set output variables
        id: vars
        run: |
          echo 'pr_body<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat updated-icons.md)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Add changeset
        run: |
          touch ./.changeset/${{ github.sha }}.md
          cat > ./.changeset/${{ github.sha }}.md << EOF
          ---
          "@utilitywarehouse/hearth-svg-icons": ${{ inputs.type }}
          "@utilitywarehouse/hearth-react-icons": ${{ inputs.type }}
          "@utilitywarehouse/hearth-react-native-icons": ${{ inputs.type }}
          ---

          EOF
          cat updated-icons.md >> ./.changeset/${{ github.sha }}.md
          rm updated-icons.md

      - name: Open pull request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5.0.3
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ inputs.branchName }}
          title: 'Generate updated icons packages'
          commit-message: 'Generate updated icons packages'
          delete-branch: true
          base: main
          body: ${{ steps.vars.outputs.pr_body }}
