name: Generate and Commit React llm Docs
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/generate-react-llm-docs.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'packages/react/**'

permissions:
  contents: write

jobs:
  generate_and_commit:
    name: Generate and Commit llm docs
    # Don't run on Versioning PRs (changeset-release/main)
    if: ${{ ! startsWith(github.ref, 'changeset-release/main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          version: 11.0.5
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}

      - name: Generate LLM docs
        run: pnpm --dir packages/react run generate:llm-docs
        env:
          NODE_OPTIONS: '--max-old-space-size=6144'

      - name: Commit Generated Files
        run: |
          git config --global user.name 'Hearth Design Systems Bot'
          git config --global user.email 'design-systems@uw.co.uk'
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Generate LLM docs'
          fi

      - name: Push Changes
        run: |
          git pull origin ${{ github.event.pull_request.head.ref }}
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
