name: Generate Icons
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'icons-release'
        type: string
      type:
        description: |
          The semver type <major|minor|patch> to bump the packages.
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

env:
  CI: true

jobs:
  generate:
    name: Generate icons packages
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - name: 🏗 Checkout code
        uses: actions/checkout@v4
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: 📦 Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_PUBLISH_TOKEN }}

      - name: 🪄 Generate SVG icons (Test)
        env:
          FIGMA_ACCESS_TOKEN: 'TEST_TOKEN'
        run: |
          echo "Checking FIGMA_ACCESS_TOKEN before running script..."
          echo "FIGMA_ACCESS_TOKEN=${FIGMA_ACCESS_TOKEN}"
          pnpm generate:svg

      - name: 🪄 Generate SVG icons
        run: FIGMA_ACCESS_TOKEN=${{ secrets.FIGMA_ACCESS_TOKEN }} pnpm generate:svg
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}

      - name: 🪄 Generate React & React Native icons
        run: pnpm generate:react

      - name: 🪄 Generate Storybook docs
        run: pnpm generate:storybook

      - name: Format files
        run: pnpm format

      - name: Set output variables
        id: vars
        run: |
          echo 'pr_body<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat updated-icons.md)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Add changeset
        run: |
          touch ./.changeset/${{ github.sha }}.md
          cat > ./.changeset/${{ github.sha }}.md << EOF
          ---
          "@utilitywarehouse/hearth-svg-icons": ${{ inputs.type }}
          "@utilitywarehouse/hearth-react-icons": ${{ inputs.type }}
          "@utilitywarehouse/hearth-react-native-icons": ${{ inputs.type }}
          ---

          EOF
          cat updated-icons.md >> ./.changeset/${{ github.sha }}.md
          rm updated-icons.md

      - name: Open pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ inputs.branchName }}
          title: 'Generate updated icons packages'
          commit-message: 'Generate updated icons packages'
          delete-branch: true
          base: main
          body: ${{ steps.vars.outputs.pr_body }}
