name: Generate SVG Assets
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch name'
        required: true
        default: 'svg-assets-release'
        type: string
      type:
        description: |
          The semver type <major|minor|patch> to bump the packages.
        required: true
        default: minor
        type: choice
        options:
          - patch
          - minor
          - major

env:
  CI: true

permissions:
  contents: read

jobs:
  generate:
    name: Generate SVG assets packages
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.28.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GLOBAL_READ_TOKEN }}

      - name: create env file
        run: |
          touch ./packages/svg-assets/.env
          echo FIGMA_ACCESS_TOKEN=${{ secrets.FIGMA_ACCESS_TOKEN }} >> ./packages/svg-assets/.env

      - name: Generate SVG assets
        run: pnpm generate:svg-assets

      - name: Format files
        run: pnpm format

      - name: Set output variables
        id: vars
        run: |
          echo 'pr_body<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat updated-svg-assets.md)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Add changeset
        run: |
          touch ./.changeset/${{ github.sha }}.md
          cat > ./.changeset/${{ github.sha }}.md << EOF
          ---
          "@utilitywarehouse/hearth-svg-assets": ${{ inputs.type }}
          ---

          EOF
          cat updated-svg-assets.md >> ./.changeset/${{ github.sha }}.md
          rm updated-svg-assets.md

      - name: Open pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.PAT }}
          branch: ${{ inputs.branchName }}
          title: 'Generate updated assets packages'
          commit-message: 'Generate updated assets packages'
          delete-branch: true
          base: main
          body: ${{ steps.vars.outputs.pr_body }}
