name: Docker Build & Push
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push-storybook:
    name: Build & Push
    runs-on:
      - nscloud-ubuntu-24.04-amd64-4x8-with-cache
      - nscloud-cache-tag-cmsv2-build
      - nscloud-cache-size-20gb
      - nscloud-exp-container-image-cache
      - nscloud-exp-runner-tool-cache-10gb
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Login to registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: registry.uw.systems
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels)
        id: metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: registry.uw.systems/design-systems/storybook
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ github.event.number }},enable=${{ github.event_name == 'pull_request' }}

      # Docker is automatically setup by using the remote Namespace runner
      # this remote runner enables better caching & more performance for container builds.
      # i.e. don't call `docker/setup-buildx-action`
      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: apps/storybook-server/Dockerfile
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          secrets: |
            npm_token=${{ secrets.NPM_GLOBAL_READ_TOKEN }}
